openapi: 3.0.0
info:
  title: eFitness-Kiosk BFF API
  version: 1.0.0
  description: API dla aplikacji eFitness-Kiosk, pośredniczące w komunikacji z eFitness.

paths:
  /auth/login:
    post:
      summary: Logowanie użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Zalogowano pomyślnie
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /users:
    post:
      summary: Rejestracja nowego użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Utworzono użytkownika

  /users/me:
    get:
      summary: Pobieranie danych zalogowanego użytkownika
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dane użytkownika
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Aktualizacja danych zalogowanego użytkownika
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Zaktualizowano dane

  /passes:
    get:
      summary: Pobieranie listy dostępnych karnetów
      responses:
        '200':
          description: Lista karnetów
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pass'

  /payments/passes/{passId}:
    post:
      summary: Inicjacja płatności za karnet
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: passId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethod:
                  type: string
                  enum: [card, transfer] # Karta (Espago) lub szybki przelew (PayU)
      responses:
        '200':
          description: Przekierowanie do płatności
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectUrl:
                    type: string

  /payments/me:
    get:
      summary: Pobieranie historii płatności zalogowanego użytkownika
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Historia płatności
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        personalData:
          type: object
        rodoConsents:
          type: array
          items:
            type: object

    Pass:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        validityPeriod:
          type: string

    Payment:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
        date:
          type: string
          format: date-time
        status:
          type: string
        paymentMethod:
          type: string
        passId:
          type: string